name: Docker build test

on:
  push:
  pull_request:
  schedule:
    - cron:  '00 17 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file 1.7.10/Dockerfile --tag my-image-name:$(date +%s)
      